### ISSUE TITLE
A feature request

### ISSUE THREAD

**Issue by morpheuslord** [josh0xA/Pantheon#1]
Hello there,

I am writing this as less of an issue and more of a feature request. It would be great If this tool had an API or a more extendable interface for more CLI-related or web-like operations. I have many Ideas where a CLI-like application like this could be great. We can talk about this on LinkedIn or Twitter if you prefer.

LinkedIn: https://www.linkedin.com/in/chiranjeevi-g-naidu/
Twitter: https://twitter.com/morpheuslord2

**Comment by josh0xA** [comment]
CLI's are boring but it'll only take like an hour to implement a CLI for Pantheon. I'll probably do it when I'm up for it
