### ISSUE TITLE
Unable to launch the app (on MacOS)

### ISSUE THREAD

**Issue by cyril-design** [josh0xA/Pantheon#3]
I'm on MacOS 12.7.3 (with Python 3.10.4) , the installation went well but when I execute `python3 pantheon.py`, here is the error message :

`macOS 12 (1207) or later required, have instead 12 (1206) !`

Has anyone resolved this issue?

Thanks

**Comment by josh0xA** [comment]
Hi Cyril, if you do not want to do a full version update, you can download the MacOS binary (from my website) listed in the README.md.
