### ISSUE TITLE
Doesn't work now....

### ISSUE THREAD

**Issue by HanYC666** [josh0xA/Pantheon#4]
I'm using a Win11 laptop with intel i5-13500H processor and this happened.
It doesn't work as expected now there's an error importing the file crawler.py from the src folder.
When I run it in VSCode, this is the output:
Traceback (most recent call last):
  File "c:\Users\Han YC\Pantheon\pantheon.py", line 44, in <module>
    from src.crawler import PantheonWebcam
ModuleNotFoundError: No module named 'src.crawler'

Please help fix this issue.
Thanks!

**Comment by josh0xA** [comment]
Please read the README.md before opening up an issue.
